In [ ]:
import torch  # torch is the deep learning library we'll use
print(torch.cuda.is_available())  # Should print: True
print(torch.cuda.get_device_name(0))  # Prints GPU model name

In [ ]:
# Install all libraries we'll need for this project

!pip install torch torchvision torchaudio
!pip install transformers
!pip install biopython
!pip install scikit-learn
!pip install pandas numpy matplotlib seaborn
!pip install kaggle

In [ ]:
# Mount Google Drive

from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Create project folder

import os

project_path = '/content/drive/MyDrive/protein_function_prediction'

os.makedirs(project_path, exist_ok=True)

print(f"Project folder created at: {project_path}")

In [ ]:
!git config --global user.name "Bhoomika Nadella"
!git config --global user.email "bhoomi.nadella@gmail.com"

In [ ]:
!git clone https://github.com/BhoomikaNadella/protein-function-prediction.git

In [ ]:
%cd protein-function-prediction

In [ ]:
from google.colab import files
import shutil


In [ ]:
gitignore_content = """
__pycache__/
*.pyc
.ipynb_checkpoints/
*.egg-info/
.env
data/raw/
models/checkpoints/
"""
with open('.gitignore', 'w') as f:  # Open file for writing
    f.write(gitignore_content)       # Write the content

In [ ]:
!git add .

In [ ]:
!git commit -m "feat: initialize Phase 1 Colab environment setup"


In [ ]:
!git remote set-url origin https://BhoomikaNadella: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@github.com/BhoomikaNadella/protein-function-prediction.git

In [ ]:
!git pull origin main --no-rebase --allow-unrelated-histories

In [ ]:
!git commit -m "merge remote and local repository histories"

In [ ]:
!git push origin main

In [ ]:

!pip install torch torchvision torchaudio
!pip install transformers
!pip install biopython
!pip install scikit-learn
!pip install pandas numpy matplotlib seaborn
!pip install kaggle

In [ ]:
import torch
import transformers
import Bio
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("All libraries loaded successfully!")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
%cd /content
!git clone https://github.com/BhoomikaNadella/protein-function-prediction.git
%cd protein-function-prediction

In [ ]:
import os
import json

# Replace with your Kaggle username
username = "bhoomikanadella13"

# Replace with your copied Kaggle token
key = "KGAT_ad24ef65172e526f6063737b2899d2ee"

# Create kaggle directory
os.makedirs('/root/.kaggle', exist_ok=True)

# Create kaggle.json manually
kaggle_config = {
    "username": username,
    "key": key
}

with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump(kaggle_config, f)

# Set permissions
os.chmod('/root/.kaggle/kaggle.json', 600)

print("Kaggle API configured successfully!")

In [ ]:
# Create project data directories

import os

os.makedirs('/content/protein-function-prediction/data/raw', exist_ok=True)
os.makedirs('/content/protein-function-prediction/data/processed', exist_ok=True)

print("Project data folders created successfully!")

In [ ]:
# Download dataset

!kaggle datasets download -d googleai/pfam-seed-random-split \
-p /content/protein-function-prediction/data/raw/

In [ ]:
# Unzip dataset

!unzip /content/protein-function-prediction/data/raw/pfam-seed-random-split.zip \
-d /content/protein-function-prediction/data/raw/

In [ ]:
# Check dataset folders

import os

base_path = "/content/protein-function-prediction/data/raw/random_split"

print("Folders inside dataset:")
print(os.listdir(base_path))

In [ ]:
# Check actual training files

train_path = "/content/protein-function-prediction/data/raw/random_split/random_split/train"

print("First 5 training files:")
print(os.listdir(train_path)[:5])

In [ ]:
# Install TensorFlow (needed to read TFRecord files)

!pip install tensorflow

In [ ]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

In [ ]:
# Path to one training file

train_file = "/content/protein-function-prediction/data/raw/random_split/random_split/train/data-00000-of-00080"

# Load TFRecord dataset

raw_dataset = tf.data.TFRecordDataset(train_file)

print("TFRecord file loaded successfully!")

In [ ]:
# Import libraries for data exploration

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

In [43]:
# Create sample protein dataset

sample_data = {
    'protein_id': ['P12345', 'P23456', 'P34567', 'P45678', 'P56789'],

    'sequence': [
        'MKTAYIAKQRQISFVKSHFSRQLEE',
        'ACDEFGHIKLMNPQRSTVWY',
        'MAEGEITTFTALTEKFNLPPGNYKKPKLLYCSNG',
        'KVFERCELARTLKRLGMDGYRGISLANWMCLAKW',
        'MAHKAMQIVKVTRGDLGAEAVDALKLAGVNRELA'
    ],

    'go_terms': [
        'GO:0003677,GO:0008270',
        'GO:0005488',
        'GO:0003677,GO:0006355,GO:0008270',
        'GO:0005515',
        'GO:0003677,GO:0005515,GO:0008270'
    ],

    'organism': ['Human', 'Mouse', 'Human', 'Yeast', 'Human']
}

print("Sample protein dataset created!")

Sample protein dataset created!


In [ ]:
# Convert sample data into a DataFrame

df = pd.DataFrame(sample_data)

print("Dataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())

In [ ]:
# Check column information

print("=== Column Data Types ===")
print(df.dtypes)

print("\n=== Missing Values ===")
print(df.isnull().sum())

In [ ]:
# Calculate protein sequence lengths

df['seq_length'] = df['sequence'].apply(len)

print("=== Sequence Length Statistics ===")
print(df['seq_length'].describe())

In [ ]:
%cd /content/protein-function-prediction

!git add .

!git commit -m "feat: add protein dataset exploration and EDA"

!git push origin main

In [ ]:
!git config --global user.name "BhoomikaNadella"
!git config --global user.email "bhoomi.nadella@gmail.com"

In [ ]:
!git push origin main

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/protein_function_prediction_phase2.ipynb" "/content/protein-function-prediction/"

%cd /content/protein-function-prediction

!git reset --soft HEAD~1

!git add .

!git commit -m "feat: add protein dataset exploration and EDA visualizations"

!git push origin main

In [36]:
!cp "/content/drive/MyDrive/Colab Notebooks/protein_function_prediction_phase2.ipynb" "/content/protein-function-prediction/"

In [37]:
!git reset --soft HEAD~1

In [38]:
%cd /content/protein-function-prediction

!git add .

!git commit -m "feat: add protein dataset exploration and EDA visualizations"

/content/protein-function-prediction
[main 5579f36] feat: add protein dataset exploration and EDA visualizations
 1 file changed, 1 insertion(+)
 create mode 100644 protein_function_prediction_phase2.ipynb


In [40]:
!git push origin main

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 3.29 KiB | 3.29 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/BhoomikaNadella/protein-function-prediction.git
   00d2054..5579f36  main -> main


In [ ]:
!git push origin main

In [ ]:
!git log --oneline

In [ ]:
!find /content -name "*.ipynb"

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/protein_function_prediction_phase2.ipynb" "/content/protein-function-prediction/"

In [ ]:
%cd /content/protein-function-prediction

!git status

In [ ]:
!git status

In [ ]:
!git add .

!git commit -m "feat: add protein dataset exploration and EDA visualizations"

!git push origin main

In [ ]:
!ls /content

# Phase 3: Data Preprocessing

In [45]:
df = pd.DataFrame(sample_data)

In [46]:
df = pd.DataFrame(sample_data)

print(df)

  protein_id                            sequence  \
0     P12345           MKTAYIAKQRQISFVKSHFSRQLEE   
1     P23456                ACDEFGHIKLMNPQRSTVWY   
2     P34567  MAEGEITTFTALTEKFNLPPGNYKKPKLLYCSNG   
3     P45678  KVFERCELARTLKRLGMDGYRGISLANWMCLAKW   
4     P56789  MAHKAMQIVKVTRGDLGAEAVDALKLAGVNRELA   

                           go_terms organism  
0             GO:0003677,GO:0008270    Human  
1                        GO:0005488    Mouse  
2  GO:0003677,GO:0006355,GO:0008270    Human  
3                        GO:0005515    Yeast  
4  GO:0003677,GO:0005515,GO:0008270    Human  


In [47]:
# Check missing values

print(df.isnull().sum())

protein_id    0
sequence      0
go_terms      0
organism      0
dtype: int64


In [48]:
# Define valid amino acids

VALID_AMINO_ACIDS = set('ACDEFGHIKLMNPQRSTVWY')

print(VALID_AMINO_ACIDS)

{'S', 'A', 'L', 'H', 'K', 'I', 'V', 'W', 'M', 'P', 'Q', 'E', 'Y', 'T', 'N', 'R', 'D', 'C', 'G', 'F'}


In [49]:
# Function to clean protein sequences

def clean_sequence(seq):

    # Check if input is actually text/string
    if not isinstance(seq, str):
        return None

    # Convert lowercase to uppercase
    seq = seq.upper()

    # Keep ONLY valid amino acids
    seq = ''.join(c for c in seq if c in VALID_AMINO_ACIDS)

    # Remove sequences shorter than 10 amino acids
    return seq if len(seq) >= 10 else None

In [50]:
# Apply cleaning function to dataset

df['cleaned_sequence'] = df['sequence'].apply(clean_sequence)

# Show original vs cleaned sequences
print(df[['sequence', 'cleaned_sequence']])

                             sequence                    cleaned_sequence
0           MKTAYIAKQRQISFVKSHFSRQLEE           MKTAYIAKQRQISFVKSHFSRQLEE
1                ACDEFGHIKLMNPQRSTVWY                ACDEFGHIKLMNPQRSTVWY
2  MAEGEITTFTALTEKFNLPPGNYKKPKLLYCSNG  MAEGEITTFTALTEKFNLPPGNYKKPKLLYCSNG
3  KVFERCELARTLKRLGMDGYRGISLANWMCLAKW  KVFERCELARTLKRLGMDGYRGISLANWMCLAKW
4  MAHKAMQIVKVTRGDLGAEAVDALKLAGVNRELA  MAHKAMQIVKVTRGDLGAEAVDALKLAGVNRELA


In [51]:
# Remove rows where cleaning returned None

df = df.dropna(subset=['cleaned_sequence'])

print("Remaining proteins after cleaning:")
print(len(df))

print("\nCleaned Dataset:")
print(df[['protein_id', 'cleaned_sequence']])

Remaining proteins after cleaning:
5

Cleaned Dataset:
  protein_id                    cleaned_sequence
0     P12345           MKTAYIAKQRQISFVKSHFSRQLEE
1     P23456                ACDEFGHIKLMNPQRSTVWY
2     P34567  MAEGEITTFTALTEKFNLPPGNYKKPKLLYCSNG
3     P45678  KVFERCELARTLKRLGMDGYRGISLANWMCLAKW
4     P56789  MAHKAMQIVKVTRGDLGAEAVDALKLAGVNRELA


In [52]:
# Function to split GO terms

def parse_go_terms(go_string):

    # Handle missing values
    if pd.isna(go_string):
        return []

    # Split labels by comma
    terms = [t.strip() for t in go_string.split(',')]

    return terms

In [53]:
# Apply GO term parsing

df['go_terms_list'] = df['go_terms'].apply(parse_go_terms)

# Show parsed GO labels
print(df[['go_terms', 'go_terms_list']])

                           go_terms                         go_terms_list
0             GO:0003677,GO:0008270              [GO:0003677, GO:0008270]
1                        GO:0005488                          [GO:0005488]
2  GO:0003677,GO:0006355,GO:0008270  [GO:0003677, GO:0006355, GO:0008270]
3                        GO:0005515                          [GO:0005515]
4  GO:0003677,GO:0005515,GO:0008270  [GO:0003677, GO:0005515, GO:0008270]


In [54]:
from sklearn.preprocessing import MultiLabelBinarizer

# Create encoder
mlb = MultiLabelBinarizer()

# Convert GO term lists into binary matrix
Y = mlb.fit_transform(df['go_terms_list'])

print("Label Matrix Shape:")
print(Y.shape)

print("\nGO Term Classes:")
print(mlb.classes_)

print("\nEncoded Labels:")
print(Y)

Label Matrix Shape:
(5, 5)

GO Term Classes:
['GO:0003677' 'GO:0005488' 'GO:0005515' 'GO:0006355' 'GO:0008270']

Encoded Labels:
[[1 0 0 0 1]
 [0 1 0 0 0]
 [1 0 0 1 1]
 [0 0 1 0 0]
 [1 0 1 0 1]]


In [55]:
# Calculate sequence lengths

df['seq_length'] = df['cleaned_sequence'].apply(len)

print(df[['cleaned_sequence', 'seq_length']])

                     cleaned_sequence  seq_length
0           MKTAYIAKQRQISFVKSHFSRQLEE          25
1                ACDEFGHIKLMNPQRSTVWY          20
2  MAEGEITTFTALTEKFNLPPGNYKKPKLLYCSNG          34
3  KVFERCELARTLKRLGMDGYRGISLANWMCLAKW          34
4  MAHKAMQIVKVTRGDLGAEAVDALKLAGVNRELA          34


In [56]:
# === FILTER LONG SEQUENCES ===

# Keep only proteins with length <= 1000
df = df[df['seq_length'] <= 1000]

print("After Length Filtering:")
print(len(df))


# === TRAIN / TEST SPLIT ===

from sklearn.model_selection import train_test_split

# Convert sequences column to Python list
sequences = df['cleaned_sequence'].tolist()

# Split dataset
X_train, X_test, Y_train, Y_test = train_test_split(
    sequences,
    Y,
    test_size=0.2,
    random_state=42
)

print("\nTrain Size:")
print(len(X_train))

print("\nTest Size:")
print(len(X_test))

print("\nTraining Label Shape:")
print(Y_train.shape)


# === SAVE PREPROCESSED DATA ===

import os
import pickle

# Create processed data folder
save_dir = '/content/protein-function-prediction/data/processed'

os.makedirs(save_dir, exist_ok=True)

# Save train sequences
pd.DataFrame({
    'sequence': X_train
}).to_csv(f'{save_dir}/train_sequences.csv', index=False)

# Save test sequences
pd.DataFrame({
    'sequence': X_test
}).to_csv(f'{save_dir}/test_sequences.csv', index=False)

# Save label arrays
np.save(f'{save_dir}/Y_train.npy', Y_train)
np.save(f'{save_dir}/Y_test.npy', Y_test)

# Save MultiLabelBinarizer encoder
with open(f'{save_dir}/mlb_encoder.pkl', 'wb') as f:
    pickle.dump(mlb, f)

print("\nAll processed files saved successfully!")

print("\nSaved Files:")
print(os.listdir(save_dir))

After Length Filtering:
5

Train Size:
4

Test Size:
1

Training Label Shape:
(4, 5)

All processed files saved successfully!

Saved Files:
['train_sequences.csv', 'Y_train.npy', 'Y_test.npy', 'mlb_encoder.pkl', 'test_sequences.csv']
